apiVersion: v1
kind: ConfigMap
metadata:
  name: d4-notify-config
  namespace: d4-notify
  labels:
    app.kubernetes.io/name: d4-notify
    app.kubernetes.io/component: config
data:
  SERVICE_NAME: "d4-notify"
  LOG_LEVEL: "info"
  APP_VERSION: "1.0.0"
  UVICORN_HOST: "0.0.0.0"
  UVICORN_PORT: "8000"
